<script lang="ts">
	import type { SiteContent } from '$lib/types/content';
	import type { ProjectWithHtml } from '$lib/server/projects';
	export let data: { content: SiteContent; projects: ProjectWithHtml[] };
	const home = data.content.home;
	const services = [['Verbouwen','Een woning laten passen bij een nieuwe manier van leven.'],['Uitbreiden','Ruimte, licht en samenhang toevoegen.'],['Nieuwbouw','Een huis vanaf de eerste lijn zorgvuldig opzetten.'],['Vergunningen','Plannen verder brengen met heldere tekeningen.']];
</script>

<section class="bg-[#f7f9fc] px-6 py-14 sm:px-8 sm:py-20"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div class="max-w-xl"><p class="text-xs font-medium uppercase tracking-[.12em] text-secondary">Maria Hoogland Architectuur</p><h1 class="mt-5 text-[clamp(2.8rem,5.5vw,5.4rem)] font-medium leading-[.96] tracking-[-.06em]">Architectuur voor wat er al is — en wat er nog moet komen.</h1><p class="mt-6 text-lg leading-8 text-secondary">Van een eerste vraag over uw woning tot een plan voor nieuwbouw of vergunning.</p><a class="mt-8 inline-block border-b border-textcolor pb-1 text-sm text-textcolor no-underline" href="/portfolio">Bekijk projecten</a></div><img class="aspect-[3/4] w-full object-cover lg:aspect-[4/3]" src={home.hero.images[0]?.src ?? 'https://picsum.photos/seed/maria-v5-opening/1200/900'} alt={home.hero.images[0]?.alt ?? 'Architectuurproject'} /></div></section>

<section class="bg-white px-6 py-16 sm:px-8 sm:py-20"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><p class="text-xs font-medium uppercase tracking-[.12em] text-secondary">Waarmee ik help</p><p class="mt-4 max-w-sm text-2xl leading-tight tracking-[-.04em]">Van een losse vraag naar een plan dat verder kan.</p></div><div class="grid border-t border-black/10 sm:grid-cols-2">{#each services as [title, copy], index}<div class={`border-b border-black/10 py-6 ${index % 2 ? 'sm:pl-8' : 'sm:pr-8'} `}><h2 class="text-xl font-semibold tracking-tight">{title}</h2><p class="mt-3 max-w-sm leading-7 text-secondary">{copy}</p></div>{/each}</div></div></section>

<section class="bg-[#e8edf4] px-6 py-20 sm:px-8 sm:py-28"><div class="mx-auto max-w-7xl"><div class="flex items-end justify-between gap-6"><div><p class="text-xs font-medium uppercase tracking-[.12em] text-secondary">Werk</p><h2 class="mt-4 text-[clamp(2.4rem,4.5vw,4.6rem)] font-medium leading-[.96] tracking-[-.06em]">Een praktijk in beelden.</h2></div><a class="hidden border-b border-textcolor pb-1 text-sm text-textcolor no-underline sm:block" href="/portfolio">Alle projecten</a></div><div class="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{#each data.projects as project, index}<a class={`text-textcolor no-underline ${index === 0 ? 'col-span-2 row-span-2' : ''}`} href={`/${project.slug}`}><img class={`w-full object-cover ${index === 0 ? 'aspect-square' : 'aspect-[4/3]'}`} src={project.mainImage} alt={project.title} loading="lazy" /><div class="mt-3 border-t border-black/15 pt-2"><p class="text-xs text-secondary">{project.category}</p><h3 class="mt-1 text-sm font-semibold sm:text-base">{project.title}</h3></div></a>{/each}</div><a class="mt-10 inline-block border-b border-textcolor pb-1 text-sm text-textcolor no-underline sm:hidden" href="/portfolio">Alle projecten</a></div></section>

<section class="bg-white px-6 py-20 sm:px-8 sm:py-24"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><img class="aspect-[4/3] w-full object-cover" src={home.hero.images[1]?.src ?? 'https://picsum.photos/seed/maria-v5-process/1000/750'} alt={home.hero.images[1]?.alt ?? 'Architectuurdetail'} /><div class="self-center"><p class="text-xs font-medium uppercase tracking-[.12em] text-secondary">Persoonlijk begeleid</p><h2 class="mt-4 max-w-xl text-[clamp(2.2rem,4vw,4rem)] font-medium leading-[.98] tracking-[-.055em]">U werkt rechtstreeks met Maria, van de eerste vraag tot het moment dat er gebouwd wordt.</h2><p class="mt-6 max-w-lg leading-7 text-secondary">Samen kijken we wat past bij de plek, uw wensen en de volgende stap.</p></div></div></section>

<section class="bg-[#f7f9fc] px-6 py-16 sm:px-8"><div class="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p class="text-xs font-medium uppercase tracking-[.12em] text-secondary">Eerste gesprek</p><h2 class="mt-4 max-w-2xl text-[clamp(2.2rem,4vw,4rem)] font-medium leading-[.98] tracking-[-.055em]">Heeft u plannen voor uw huis of gebouw?</h2></div><a class="border border-secondary px-5 py-3 text-sm text-textcolor no-underline hover:bg-secondary hover:text-white" href="/contact">Vertel over uw plannen</a></div></section>
